# Generated by Django 3.2.8 on 2021-10-27 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('FullName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Key', models.CharField(max_length=200)),
                ('MAC_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Device', models.CharField(blank=True, max_length=200, null=True)),
                ('Username', models.CharField(blank=True, max_length=200, null=True)),
                ('UsageDateAndTime', models.CharField(blank=True, max_length=200, null=True)),
                ('Temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('pHin', models.CharField(blank=True, max_length=200, null=True)),
                ('TDSin', models.CharField(blank=True, max_length=200, null=True)),
                ('pHout', models.CharField(blank=True, max_length=200, null=True)),
                ('TDSout', models.CharField(blank=True, max_length=200, null=True)),
                ('MotorONInSeconds', models.CharField(blank=True, max_length=200, null=True)),
                ('VolumeSampled', models.CharField(blank=True, max_length=200, null=True)),
                ('NoOfHourUsed', models.CharField(blank=True, max_length=200, null=True)),
                ('CartridgeLifeLeft', models.CharField(blank=True, max_length=200, null=True)),
                ('OperationStatus', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
